@startuml

class Provider <<(P, yellow) Provider>> {
  ~store
}

class App {

}

'Header
class AppHeader {

}

class SearchBarContainer <<(C, red) Container>> {
  ~store
  ==methods==
  handleSearchClick(keyword)
}

class SearchBar {
  ==props==
  onSearchClicked
  ==methods==
  handleSearchClick(keyword)
}

'LeftPanel
class LeftPanel {

}

class UserLibraryListContainer <<(C, red) Container>> {
  ==props==
  ~store
  ==methods==
  handleDeleteClick(libraryID)
}

class UserLibraryList {
  ==props==
  libraryList: Object
  onDeleteClicked(libraryID)
  ==methods==
  handleDeleteClick(libraryID)
}

'LibraryRegistrationPanel'
class LibraryRegistrationPanelContainer <<(C, red) Container>> {
  ~store
  ==methods==
  handleKeywordChange(keyword)
  handlePrefChange(prefectural)
  handleCityChange(city)
}

class LibraryRegistrationPanel {
  ==props==
  isInitialState
  isSucceededRegistration
  libraryList
  onKeywordChanged(keyword)
  onPrefChanged(prefectural)
  onCityChanged(city)
  ==methods==
  handleKeywordChange(keyword)
  handlePrefChange(prefectural)
  handleCityChange(city)
}

class LibraryRegistrationPanelHeader {
  ==props==
  onKeywordChanged(keyword)
  onPrefChanged(prefectural)
  onCityChanged(city)
  ==methods==
  handleKeywordChange(keyword)
  handlePrefChange(prefectural)
  handleCityChange(city)
}

class FilteredLibraryList {
  ==props==
  libraryList: object
  onLibraryAddClicked(libraryID)
  ==methods==
  handleLibraryAddClick(libraryID)
}

'BookInfo'
class BookInfoListContainer <<(C, red)Container>> {
  ~store
}

class BookInfoList {
  ==props==
  bookInfoList: Object
  isSearching: boolean
}

class BookInfo {
  ==props==
  bookInfo: Object
}


Provider o-- App

  App o-- AppHeader
    AppHeader o-- SearchBarContainer
      SearchBarContainer o-- SearchBar
      SearchBarContainer "handleSearchClick" <.. "onSearchClicked" SearchBar

  App o-- LeftPanel
    LeftPanel o-- UserLibraryListContainer
      UserLibraryListContainer o-- UserLibraryList
      UserLibraryListContainer "handleDeleteClick" <.. "onDeleteClicked" UserLibraryList

  App o-- MainPanel
    MainPanel o-- Route
      Route o-- ServiceIntroduction
      Route o-- LibraryRegistrationPanelContainer
        LibraryRegistrationPanelContainer o-- LibraryRegistrationPanel
        LibraryRegistrationPanelContainer "handleXXX" <.. "onXXXChanged" LibraryRegistrationPanel
          LibraryRegistrationPanel o-- LibraryRegistrationPanelHeader
          LibraryRegistrationPanel "handleXXX" <.. "onXXXChanged" LibraryRegistrationPanelHeader
          LibraryRegistrationPanel o-- FilteredLibraryList
          LibraryRegistrationPanel "handleXXX"  <.. "onXXXChanged" FilteredLibraryList
      Route o-- BookInfoListContainer
        BookInfoListContainer o-- BookInfoList
          BookInfoList o-- BookInfo
          BookInfoList o-- BookSearchingPanel


@enduml
