name: Build and Deploy
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: 
      - blog-updated

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
      - name: Checkout blog repository
        uses: actions/checkout@v2
        with:
          repository: horitaka/book-search-blog
          token: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}
          path: blog
      - name: Install Dependencies
        run: |
          cd blog
          npm ci    
      - name: Build blog app
        run: |
          cd blog
          ./node_modules/.bin/gatsby build
      - name: Upload blog files
        uses: actions/upload-artifact@master
        with:
          name: blog
          path: blog/public       
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: blog
          path: build/blog
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
